### ISSUE TITLE
Project setup

### ISSUE THREAD

**Issue by Journeycorner** [stephanrauh/JSF-on-Spring-Boot#1]
## Project setup

By running the application the beans don't get injected, however your hint to copy the class files of an eclipse bin folder to src/...classes is confusing:
- Why put class files into a src folder? This seems contradictory - but I'm new to Spring Boot.
- I use IntelliJ, copying the output of the classes to webapp/classes didn't help

Can you please give an example about the contents of this folder?
## Dependencies

The dependencies of Mojarra are set to "2.+" which could be an issue, since 2.2.11 [conflicts](http://www.beyondjava.net/blog/updating-to-mojarra-2-2-11-may-break-your-spring-boot-application/) with Spring Boot - cool blog btw ;-).

**Comment by stephanrauh** [comment]
Let's start with the questions. 

You are right, it sounds a bit odd to copy the class file into a source folder. Thing become clearer when you read the full name of the folder. It continues with "WEB-INF/classes". That's the folder Tomcat adds to the class path. Thing is, Maven and Gradle copy the entire folder src/webapp to the web application folder of Tomcat. Setting the output folder of Eclipse - or of IntelliJ, for that matter - to ```src/webapp/WEB-INF/classes" makes sure that the classes are copied to the correct Tomcat folder. Usually you don't have to care about the because the IDE copies the files for you. However, the IDEs don't know Spring Boot, so they need a little help. Among other things, Spring Boots doesn't need to copy the files, so it's a good idea to put the files where they belong from start.

BTW, that's also the reason why `webapp/classes` didn't help you. It has to be `src/webapp/WEB-INF/classes`. If you project setup looks different: look for the folder containing your index.html. The target class folder is the subfolder ``WEB-INF/classes`´ of that folder.

**Comment by stephanrauh** [comment]
![image](https://cloud.githubusercontent.com/assets/3045767/8765232/c758a2ac-2e03-11e5-8286-12fe8e94aa64.png)

**Comment by stephanrauh** [comment]
![image](https://cloud.githubusercontent.com/assets/3045767/8765244/0edcec14-2e04-11e5-945e-5e4b7079d5b3.png)

**Comment by stephanrauh** [comment]
![image](https://cloud.githubusercontent.com/assets/3045767/8765249/45204028-2e04-11e5-9200-34a982376fa3.png)

**Comment by stephanrauh** [comment]
- The "Understanding Scopes" project works fine as a Maven project. 
- The other two projects can't resolve their managed JSF beans.

Until I've solved the problem, I recommend you start with the "Understanding Scopes" project.

**Comment by Journeycorner** [comment]
Thanks a million - "Understanding Scopes" works fine!

BTW: Maybe Port 81 would be a better default choice, since the widely spread Skype uses [Port 80 on Windows](https://support.skype.com/de/faq/FA148/welche-ports-mussen-offen-zu-verwenden-sein-skype-for-windows-desktop).

**Comment by stephanrauh** [comment]
Thanks for the hint! Port 80 is nice because it's the default port of the browser, too :).
